// src/constants.js

export const TRANSLATIONS = {
  en: {
    labGrown: "LAB-GROWN",
    diamondStudio: "DIAMOND STUDIO",
    diamonds: "Diamonds",
    rings: "Engagement rings",
    earrings: "Earrings",
    whyLab: "Why lab-grown",
    heroTitle: "Ethically brilliant. Forever flawless.",
    heroDesc: "Discover curated lab-grown diamonds and engagement rings with locked-in triple-excellent cut, polish and symmetry.",
    alwaysEx: "Always 3× Excellent",
    grading: "IGI / GIA grading",
    quickFilter: "Quick filter",
    designInSeconds: "Design your jewel in seconds.",
    shape: "Shape",
    allShapes: "All shapes",
    clarity: "Clarity",
    anyClarity: "Any clarity",
    colour: "Colour",
    allColours: "All colours",
    search: "Search",
    searchPlaceholder: "Shape, clarity, ring, carat…",
    curated: "Curated selection",
    designsMatch: "designs match.",
    from: "From",
    addToBasket: "Add",
    designJewel: "Design",
    basket: "Basket",
    emptyBasket: "Your basket is empty.",
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    checkout: "Checkout",
    placeOrder: "Place Order",
    back: "Back",
    shippingAddress: "Shipping Address",
    paymentMethod: "Payment Method",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    street: "Street",
    postalCode: "Postal Code",
    city: "City",
    cardName: "Name on Card",
    cardNumber: "Card Number",
    expiry: "Expiry",
    cvc: "CVC",
    orderConfirmed: "Order Confirmed",
    thankYou: "Thank you for your purchase.",
    close: "Close",
    builderTitle: "Jewelry Builder",
    builderDesc: "Create a setting that perfectly frames your chosen diamond.",
    centerStone: "Centre stone selected",
    settingStyle: "Setting style",
    metal: "Metal",
    ringSize: "Ring size (EU)",
    backingType: "Backing Type",
    estPrice: "Estimated price",
    addToCart: "Add to basket",
    cancel: "Cancel",
    typeRing: "Ring",
    typeEarring: "Earring",
    education: "Education",
    language: "Language",
    priceLimit: "Price Range",
    qualityNote: "Uncompromised Quality: Every single diamond is Triple Excellent (Cut, Polish, Symmetry) and comes with an official IGI certificate.",
    maxPrice: "Max Price",
    
    // Chatbot Specific
    chatTitle: "Diamond Expert",
    chatPlaceholder: "Select an option or type...",
    chatWelcome: "Hello! I am your virtual diamond concierge. How can I assist you today?",
    chatOptOrder: "Track Order",
    chatOptStock: "Check Stock",
    chatOptEdu: "Diamond Education",
    chatOptPolicy: "Shipping & Returns",
    chatOptAgent: "Human Support",
    chatOptMain: "Main Menu",
    
    // Chat Flows
    chatAskOrder: "Please enter your Order ID (e.g., #1234).",
    chatErrOrder: "That doesn't look like a valid ID. It should be a '#' followed by 4 digits (e.g., #1234).",
    chatFoundOrder: "Order found: Currently in 'Quality Control'. Expected delivery: 2 Days.",
    chatAskShape: "Which diamond shape are you interested in?",
    chatStockResult: "We currently have excellent inventory for that shape starting from CHF 890.",
    chatEduIntro: "What would you like to learn about?",
    chatEduCut: "Cut is the most important factor for sparkle. We only sell 'Excellent' or 'Ideal' cuts.",
    chatEduColor: "We focus on colorless grades (D, E, F) to ensure your diamond looks icy white.",
    chatEduClarity: "Clarity measures internal features. We recommend VS2 or higher for an eye-clean look.",
    chatPolicyShip: "Shipping is free and fully insured for orders over CHF 3,000. Delivery takes 2-4 business days.",
    chatPolicyReturn: "We offer a 30-day return policy for a full refund on all standard items.",
    chatAgent: "You can reach our concierge team at support@diamondstudio.ch or +41 44 123 45 67."
  },
  de: {
    labGrown: "LABOR-DIAMANTEN",
    diamondStudio: "DIAMANT STUDIO",
    diamonds: "Diamanten",
    rings: "Verlobungsringe",
    earrings: "Ohrringe",
    whyLab: "Warum Labor-Diamanten",
    heroTitle: "Ethisch brillant. Für immer makellos.",
    heroDesc: "Entdecken Sie kuratierte Labor-Diamanten und Verlobungsringe mit garantiertem 3-fach exzellentem Schliff.",
    alwaysEx: "Immer 3× Exzellent",
    grading: "IGI / GIA Zertifikat",
    quickFilter: "Schnellfilter",
    designInSeconds: "Entwerfen Sie Ihr Schmuckstück in Sekunden.",
    shape: "Form",
    allShapes: "Alle Formen",
    clarity: "Reinheit",
    anyClarity: "Jede Reinheit",
    colour: "Farbe",
    allColours: "Alle Farben",
    search: "Suche",
    searchPlaceholder: "Form, Reinheit, Ring, Karat…",
    curated: "Kuratierte Auswahl",
    designsMatch: "Designs gefunden.",
    from: "Ab",
    addToBasket: "Hinzufügen",
    designJewel: "Designen",
    basket: "Warenkorb",
    emptyBasket: "Ihr Warenkorb ist leer.",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    total: "Gesamt",
    checkout: "Kasse",
    placeOrder: "Bestellen",
    back: "Zurück",
    shippingAddress: "Lieferadresse",
    paymentMethod: "Zahlungsmethode",
    firstName: "Vorname",
    lastName: "Nachname",
    email: "E-Mail",
    street: "Straße",
    postalCode: "PLZ",
    city: "Stadt",
    cardName: "Name auf Karte",
    cardNumber: "Kartennummer",
    expiry: "Gültig bis",
    cvc: "Prüfziffer",
    orderConfirmed: "Bestellung bestätigt",
    thankYou: "Vielen Dank für Ihren Einkauf.",
    close: "Schließen",
    builderTitle: "Schmuck Konfigurator",
    builderDesc: "Erstellen Sie eine Fassung, die Ihren Diamanten perfekt in Szene setzt.",
    centerStone: "Gewählter Diamant",
    settingStyle: "Fassungsstil",
    metal: "Metall",
    ringSize: "Ringgröße (EU)",
    backingType: "Verschlussart",
    estPrice: "Geschätzter Preis",
    addToCart: "In den Warenkorb",
    cancel: "Abbrechen",
    typeRing: "Ring",
    typeEarring: "Ohrring",
    education: "Wissen",
    language: "Sprache",
    priceLimit: "Preisrahmen",
    qualityNote: "Kompromisslose Qualität: Jeder Diamant ist 3-fach Exzellent (Schliff, Politur, Symmetrie) und besitzt ein offizielles IGI-Zertifikat.",
    maxPrice: "Maximalpreis",

    // Chatbot Specific
    chatTitle: "Diamant Experte",
    chatPlaceholder: "Wählen Sie eine Option...",
    chatWelcome: "Hallo! Ich bin Ihr virtueller Diamant-Concierge. Wie kann ich Ihnen heute helfen?",
    chatOptOrder: "Bestellung verfolgen",
    chatOptStock: "Lagerbestand prüfen",
    chatOptEdu: "Diamant Wissen",
    chatOptPolicy: "Versand & Rückgabe",
    chatOptAgent: "Persönlicher Support",
    chatOptMain: "Hauptmenü",

    // Chat Flows
    chatAskOrder: "Bitte geben Sie Ihre Bestellnummer ein (z.B. #1234).",
    chatErrOrder: "Das sieht nicht wie eine gültige ID aus. Bitte Format '#1234' verwenden.",
    chatFoundOrder: "Bestellung gefunden: Aktuell in der 'Qualitätskontrolle'. Erwartete Lieferung: 2 Tage.",
    chatAskShape: "An welcher Diamantform sind Sie interessiert?",
    chatStockResult: "Wir haben einen hervorragenden Bestand für diese Form ab CHF 890.",
    chatEduIntro: "Worüber möchten Sie mehr erfahren?",
    chatEduCut: "Der Schliff ist der wichtigste Faktor für das Funkeln. Wir verkaufen nur 'Excellent' or 'Ideal'.",
    chatEduColor: "Wir konzentrieren uns auf farblose Grade (D, E, F) für maximales Strahlen.",
    chatEduClarity: "Reinheit misst innere Merkmale. Wir empfehlen VS2 oder höher für lupenreine Optik.",
    chatPolicyShip: "Versand ist kostenlos und versichert ab CHF 3.000. Lieferung dauert 2-4 Werktage.",
    chatPolicyReturn: "Wir bieten ein 30-tägiges Rückgaberecht mit voller Rückerstattung.",
    chatAgent: "Sie erreichen unser Team unter support@diamondstudio.ch oder +41 44 123 45 67."
  },
  fr: {
    labGrown: "DIAMANTS DE LABO",
    diamondStudio: "STUDIO DIAMANT",
    diamonds: "Diamants",
    rings: "Bagues de fiançailles",
    earrings: "Boucles d'oreilles",
    whyLab: "Pourquoi le laboratoire",
    heroTitle: "Éthiquement brillant. Toujours sans défaut.",
    heroDesc: "Découvrez des diamants de laboratoire et des bagues de fiançailles avec une coupe, un polissage et une symétrie 3× excellents.",
    alwaysEx: "Toujours 3× Excellent",
    grading: "Certifié IGI / GIA",
    quickFilter: "Filtre rapide",
    designInSeconds: "Créez votre bijou en quelques secondes.",
    shape: "Forme",
    allShapes: "Toutes formes",
    clarity: "Pureté",
    anyClarity: "Toute pureté",
    colour: "Couleur",
    allColours: "Toutes couleurs",
    search: "Rechercher",
    searchPlaceholder: "Forme, pureté, bague, carat…",
    curated: "Sélection",
    designsMatch: "designs trouvés.",
    from: "À partir de",
    addToBasket: "Ajouter",
    designJewel: "Créer",
    basket: "Panier",
    emptyBasket: "Votre panier est vide.",
    subtotal: "Sous-total",
    shipping: "Livraison",
    total: "Total",
    checkout: "Paiement",
    placeOrder: "Commander",
    back: "Retour",
    shippingAddress: "Adresse de livraison",
    paymentMethod: "Moyen de paiement",
    firstName: "Prénom",
    lastName: "Nom",
    email: "E-mail",
    street: "Rue",
    postalCode: "Code postal",
    city: "Ville",
    cardName: "Nom sur la carte",
    cardNumber: "Numéro de carte",
    expiry: "Expiration",
    cvc: "CVC",
    orderConfirmed: "Commande confirmée",
    thankYou: "Merci pour votre achat.",
    close: "Fermer",
    builderTitle: "Créateur de Bijoux",
    builderDesc: "Créez une monture qui met parfaitement en valeur votre diamant.",
    centerStone: "Diamant sélectionné",
    settingStyle: "Style de monture",
    metal: "Métal",
    ringSize: "Taille de bague (EU)",
    backingType: "Type de fermoir",
    estPrice: "Prix estimé",
    addToCart: "Ajouter au panier",
    cancel: "Annuler",
    typeRing: "Bague",
    typeEarring: "Boucle",
    education: "Éducation",
    language: "Langue",
    priceLimit: "Fourchette de prix",
    qualityNote: "Qualité sans compromis : Chaque diamant est 3x Excellent (Taille, Polissage, Symétrie) et est accompagné d'un certificat IGI officiel.",
    maxPrice: "Prix max",

    // Chatbot Specific
    chatTitle: "Expert Diamant",
    chatPlaceholder: "Choisissez une option...",
    chatWelcome: "Bonjour ! Je suis votre concierge virtuel. Comment puis-je vous aider ?",
    chatOptOrder: "Suivre commande",
    chatOptStock: "Vérifier stock",
    chatOptEdu: "Éducation",
    chatOptPolicy: "Livraison & Retours",
    chatOptAgent: "Support humain",
    chatOptMain: "Menu principal",

    // Chat Flows
    chatAskOrder: "Veuillez entrer votre numéro de commande (ex: #1234).",
    chatErrOrder: "Format invalide. Utilisez le format '#1234'.",
    chatFoundOrder: "Commande trouvée : Actuellement en 'Contrôle Qualité'. Livraison prévue : 2 jours.",
    chatAskShape: "Quelle forme de diamant vous intéresse ?",
    chatStockResult: "Nous avons un excellent inventaire pour cette forme à partir de CHF 890.",
    chatEduIntro: "Que souhaitez-vous apprendre ?",
    chatEduCut: "La taille (Cut) est le facteur clé pour l'éclat. Nous ne vendons que de l'Excellent.",
    chatEduColor: "Nous privilégions les grades incolores (D, E, F) pour une brillance glacée.",
    chatEduClarity: "La pureté mesure les inclusions. Nous recommandons VS2 ou plus.",
    chatPolicyShip: "Livraison gratuite et assurée au-delà de CHF 3.000. Délais de 2-4 jours ouvrables.",
    chatPolicyReturn: "Nous offrons une politique de retour de 30 jours avec remboursement intégral.",
    chatAgent: "Vous pouvez contacter notre équipe à support@diamondstudio.ch ou au +41 44 123 45 67."
  },
  it: {
    labGrown: "DIAMANTI LAB",
    diamondStudio: "STUDIO DIAMANTE",
    diamonds: "Diamanti",
    rings: "Anelli di fidanzamento",
    earrings: "Orecchini",
    whyLab: "Perché laboratorio",
    heroTitle: "Eticamente brillante. Per sempre perfetto.",
    heroDesc: "Scopri diamanti coltivati in laboratorio e anelli di fidanzamento con taglio, politura e simmetria 3× eccellenti.",
    alwaysEx: "Sempre 3× Eccellente",
    grading: "Certificato IGI / GIA",
    quickFilter: "Filtro rapido",
    designInSeconds: "Progetta il tuo gioiello in pochi secondi.",
    shape: "Forma",
    allShapes: "Tutte le forme",
    clarity: "Purezza",
    anyClarity: "Qualsiasi purezza",
    colour: "Colore",
    allColours: "Tutti i colori",
    search: "Cerca",
    searchPlaceholder: "Forma, purezza, anello, carati…",
    curated: "Selezione curata",
    designsMatch: "design trovati.",
    from: "Da",
    addToBasket: "Aggiungi",
    designJewel: "Crea",
    basket: "Carrello",
    emptyBasket: "Il tuo carrello è vuoto.",
    subtotal: "Subtotale",
    shipping: "Spedizione",
    total: "Totale",
    checkout: "Pagamento",
    placeOrder: "Ordina",
    back: "Indietro",
    shippingAddress: "Indirizzo di spedizione",
    paymentMethod: "Metodo di pagamento",
    firstName: "Nome",
    lastName: "Cognome",
    email: "Email",
    street: "Via",
    postalCode: "CAP",
    city: "Città",
    cardName: "Nome sulla carta",
    cardNumber: "Numero carta",
    expiry: "Scadenza",
    cvc: "CVC",
    orderConfirmed: "Ordine confermato",
    thankYou: "Grazie per il tuo acquisto.",
    close: "Chiudi",
    builderTitle: "Costruttore Gioielli",
    builderDesc: "Crea una montatura che incornicia perfettamente il tuo diamante.",
    centerStone: "Diamante selezionato",
    settingStyle: "Stile montatura",
    metal: "Metallo",
    ringSize: "Misura anello (EU)",
    backingType: "Chiusura",
    estPrice: "Prezzo stimato",
    addToCart: "Aggiungi al carrello",
    cancel: "Annulla",
    typeRing: "Anello",
    typeEarring: "Orecchino",
    education: "Istruzione",
    language: "Lingua",
    priceLimit: "Limite di prezzo",
    qualityNote: "Qualità senza compromessi: Ogni singolo diamante è Triplo Eccellente (Taglio, Politura, Simmetria) e viene fornito con un certificato IGI ufficiale.",
    maxPrice: "Prezzo max",

    // Chatbot Specific
    chatTitle: "Esperto Diamanti",
    chatPlaceholder: "Seleziona un'opzione...",
    chatWelcome: "Ciao! Sono il tuo concierge virtuale. Come posso aiutarti oggi?",
    chatOptOrder: "Traccia ordine",
    chatOptStock: "Controlla stock",
    chatOptEdu: "Istruzione",
    chatOptPolicy: "Spedizione & Resi",
    chatOptAgent: "Supporto umano",
    chatOptMain: "Menu principale",

    // Chat Flows
    chatAskOrder: "Inserisci il numero dell'ordine (es. #1234).",
    chatErrOrder: "Formato non valido. Usa il formato '#1234'.",
    chatFoundOrder: "Ordine trovato: Attualmente in 'Controllo Qualità'. Consegna prevista: 2 giorni.",
    chatAskShape: "A quale forma di diamante sei interessato?",
    chatStockResult: "Abbiamo un eccellente inventario per questa forma a partire da CHF 890.",
    chatEduIntro: "Cosa ti piacerebbe imparare?",
    chatEduCut: "Il taglio (Cut) è il fattore più importante per la brillantezza. Vendiamo solo 'Eccellente'.",
    chatEduColor: "Ci concentriamo sui gradi incolori (D, E, F) per il massimo splendore.",
    chatEduClarity: "La purezza misura le caratteristiche interne. Consigliamo VS2 o superiore.",
    chatPolicyShip: "Spedizione gratuita e assicurata sopra i 3.000 CHF. Consegna in 2-4 giorni lavorativi.",
    chatPolicyReturn: "Offriamo una politica di reso di 30 giorni con rimborso completo.",
    chatAgent: "Puoi contattare il nostro team a support@diamondstudio.ch o +41 44 123 45 67."
  }
};

export const DIAMOND_SHAPES = [
  "Round",
  "Oval",
  "Princess",
  "Emerald",
  "Cushion",
  "Pear",
  "Radiant",
  "Asscher",
];

export const CLARITIES = ["VS2", "VS1", "VVS2", "VVS1", "IF"];
export const CLARITY_ORDER = ["VS2", "VS1", "VVS2", "VVS1", "IF"];
export const COLORS = ["D", "E", "F"];

export const CLARITY_DESCRIPTIONS = {
  VS2: "VS2 · very slightly included",
  VS1: "VS1 · very slightly included",
  VVS2: "VVS2 · very very slightly included",
  VVS1: "VVS1 · very very slightly included",
  IF: "IF · internally flawless",
};

export const COLOR_DESCRIPTIONS = {
  D: "D · colorless",
  E: "E · colorless",
  F: "F · near colorless",
};

export const SETTING_OPTIONS = ["Solitaire", "Halo", "Three-stone", "Pavé band"];
export const EARRING_SETTINGS = ["Studs", "Halo Studs", "Martini", "Drop"];

export const METAL_OPTIONS = ["Platinum", "18k White Gold", "18k Yellow Gold", "18k Rose Gold"];
export const SIZE_OPTIONS = ["50 (EU)", "52 (EU)", "54 (EU)", "56 (EU)", "58 (EU)", "60 (EU)"];
export const BACKING_OPTIONS = ["Push Back", "Screw Back"];

export const SETTING_PRICES = {
  Solitaire: 590,
  Halo: 890,
  "Three-stone": 1150,
  "Pavé band": 790,
  "Studs": 390,
  "Halo Studs": 690,
  "Martini": 450,
  "Drop": 550
};

export const METAL_PRICES = {
  Platinum: 450,
  "18k White Gold": 0,
  "18k Yellow Gold": 0,
  "18k Rose Gold": 0,
};

export const SETTING_DESCRIPTIONS = {
  Solitaire: "Timeless, minimal setting that spotlights the centre stone.",
  Halo: "A halo of fine diamonds amplifying the centre stone’s presence.",
  "Three-stone": "Two side stones symbolising past, present and future.",
  "Pavé band": "Refined band with pavé-set diamonds for continuous sparkle.",
  "Studs": "Classic four-prong setting for maximum brilliance.",
  "Halo Studs": "Surrounded by micro-pavé diamonds for extra size.",
  "Martini": "Three-prong setting that sits flush against the ear.",
  "Drop": "Elegant drop design for movement and light catch."
};